### PR TITLE
HCal Clustering

### PR DESCRIPTION
**Pull request by sophiemiddleton**
- Adds a HcalCluster to Event Bus
- Algorithms based on Ecal clustering

### CODE REVIEW

**Review by tomeichlersmith — COMMENTED** [review]
I haven't had a chance to pull this down and look at it in more detail, but a few general discussion points.

A lot of this clustering structure is similar to what is in the ECal. Do you have plans to edit this structure? The "vision" for `TemplatedClusterFinder` is that _everyone_ would use the same `WorkingCluster`, `TemplatedClusterFinder`, etc... but inidividuals would have their own weight class (i.e. `MyWeightClass` would be split into an `EcalClusterWeighting` and `HcalClusterWeighting` and that is where the sub-system dependence would come in). Maybe we could move the clustering structure to `Tools` and then Hcal and Ecal could share it?
This whole points is moot if you plan to drastically change the clustering procedure compared to the ECal.

The format of many of these source files is still in the "old" style. You can update the format by running the following in a `bash` environment.
```
cd Hcal
find . -type f -name "*.h" -o -name "*.cxx" -exec clang-format -i --style=Google {} \;
```
If you can't get this to work, I can do it for you.

**Comment by sophiemiddleton** [comment]
Hi Tom, I think there are some differences in the TemplateClusterFinder (and more might be added). The Working Cluster again I added a few things. Your suggestion led to the following error (at SLAC): 

```
find: ‘clang-format’: No such file or directory
```

At the moment the weight class is pretty much the same so this is probably going to need updating at some point

**Comment by sophiemiddleton** [comment]
Hi,

Is there any update on this?

**Review by tomeichlersmith — APPROVED** [review]
Sorry Sophie. I lost track of this PR. I've formatted the files and I agree with you that this high-level of a reconstruction benefits from separating the Ecal and Hcal.

**Comment by sophiemiddleton** [comment]
Hi Everyone,

Just noticed that this was not yet merged - were there any issues?

Thanks,
Sophie

**Comment by tomeichlersmith** [comment]
@sophiemiddleton I put a rebase of this branch onto a new branch that I merged into Hcal/trunk manually. These changes should be on `trunk` except for some changes in the test files that weren't propagated to your branch.

**Pull request closed without merging**
