### PR TITLE
Add pedestal producer

### PR DESCRIPTION
**Pull request by jmmans**
Standardized pedestal calculation tool, includes various data-quality cuts.  Produces optional histograms as well as calibration files in standard formats.

### CODE REVIEW

**Comment by cmantill** [comment]
hi @jmmans, a small comment, can you move `exampleConfigs/ ` to the [test](https://github.com/LDMX-Software/Hcal/tree/trunk/test) directory?

**Comment by jmmans** [comment]
> hi @jmmans, a small comment, can you move `exampleConfigs/ ` to the [test](https://github.com/LDMX-Software/Hcal/tree/trunk/test) directory?

Hi @cmantill , so it isn't a test configuration -- it's the exact configuration to run to make the pedestal output.  The test directory looks like actual tests, no?  Also @tomeichlersmith said this was the (new) place for this sort of thing -- I don't have a strong preference, but I do think that a standard place would be good.

**Comment by tomeichlersmith** [comment]
I think having a place for config scripts that is _separate_ from the `test` directory is good, especially since we will want to share configs that aren't used in testing.
I suggested the directory `exampleConfigs` because the TrigScint already has a directory like that in their submodule, so I think it makes sense.

**Comment by cmantill** [comment]
Ok, makes sense thanks for clarifying!

**Review by tomeichlersmith — APPROVED** [review]
Looks good to me. I will _not_ use my admin privileges here to await comment from @mrsolt or @cmantill .

**Review by mrsolt — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
